version: "3.5"

services:
  nginx:
    container_name: surface-nginx
    build: ./nginx
    volumes:
      - ./api/static:/home/app/web/staticfiles
      - ./data:/home/app/web/data
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    env_file:
      - api/production.env
    environment:
      HOST_FQDN: $HOST_FQDN
      WEBMASTER_EMAIL: $WEBMASTER_EMAIL
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  cache:
    container_name: surface-cache
    image: memcached
    restart: unless-stopped

  redis:
    container_name: surface-redis
    image: redis
    restart: unless-stopped

  postgres:
    container_name: surface-database
    image: timescale/timescaledb-postgis:2.3.0-pg13
    restart: unless-stopped
    env_file:
      - api/production.env
    volumes:
      - ./:/app
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  api:
    build:
      dockerfile: Dockerfile
      context: api
    container_name: surface-api
    command: ./startup.sh
    env_file:
      - api/production.env
    restart: unless-stopped
    volumes:
      - ./api:/surface
      - ./data/media:/data/media
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
      - ./data/exported_data:/data/exported_data
      - ./data/documents:/data/documents
    depends_on:
      - postgres
      - cache
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    expose:
      - 8000

  celery_worker:
    build:
      dockerfile: Dockerfile
      context: api
    container_name: surface-celery-worker
    command: /home/surface/.local/bin/celery -A tempestas_api worker -l info
    env_file:
      - api/production.env
    restart: unless-stopped
    volumes:
      - ./api:/surface
      - ./data/documents/ingest:/data/documents/ingest
      - ./data/exported_data:/data/exported_data
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
    depends_on:
      - api
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  celery_beat:
    build:
      dockerfile: Dockerfile
      context: api
    container_name: surface-celery-beat
    restart: unless-stopped
    command: /home/surface/.local/bin/celery -A tempestas_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - api/production.env
    volumes:
      - ./api:/surface
      - ./data/postgresql:/data
    depends_on:
      - api
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"